name: "Setup environment"
description: "Checkout repo, setup Python from pyproject.toml, setup uv, and restore caches"

inputs:
  fetch-depth:
    description: "Git fetch depth"
    default: "1"

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Set up Python
      uses: actions/setup-python@v6

    - name: Set up UV
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
