name: PR Checks

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        uses: fdmorison/tiozin/.github/actions/setup-env@main
        with:
          fetch-depth: 0

      - name: Check PR Title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            perf
            refactor
            chore
            docs
            test
            style
            ci
            build
          scopes: |
            core
            tio_kernel
            tio_duckdb
            tio_spark
            claude
          requireScope: true

      - name: Check Commits
        uses: wagoid/commitlint-github-action@v6

      - name: Check Release Intent
        uses: fdmorison/tiozin/.github/actions/check-release-intent@main

      - name: Install Dependencies
        run: make install-dev

      - name: Lint
        run: make check

      - name: Tests
        run: make test
