name: PR Meta

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read
  pull-requests: read

jobs:
  meta:
    if: ${{ !startsWith(github.head_ref, 'release-please--') }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        uses: fdmorison/tiozin/.github/actions/setup-env@main
        with:
          fetch-depth: 0

      - name: Check PR Title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            perf
            refactor
            chore
            docs
            test
            style
            ci
            build
          scopes: |
            core
            core-api
            core-cli
            core-utils
            core-compose
            tio_kernel
            tio_duckdb
            tio_spark
            harness
          requireScope: true

      - name: Check Commits
        uses: wagoid/commitlint-github-action@v6

      - name: Check Release Intent
        uses: fdmorison/tiozin/.github/actions/check-release-intent@main
